// Generated by protoparser macro_install sync
// Use in PML with:
// @macros_import ".protoml/macro-packs/macros.index.pml"
@macro contract-kit_sample ".protoml/macro-packs/contract-kit/macros/contract-kit_sample.pml"
@macro base-kit_sample ".protoml/macro-packs/base-kit/macros/base-kit_sample.pml"
